---
title: "GISRUK Mentorship Scheme"
---


The GISRUK conference series is trialling a **mentorship scheme** for conference attendees. This provides those who define themselves as ECRs (Early Career Researchers) an opportunity to discuss career development with a more experienced person in the field.

This scheme is completely voluntary, but we hope it enables conversations between people at different career stages, and offers an alternative line of support and advice to ECRs outside of other avenues.
    
# Details and expectations

- The scheme runs for **12 months** between the annual GISRUK conference events, usually held in April.
- Mentors and mentees (ECRs) can sign-up to the scheme in the days before the GISRUK conference once they are registered to attend.
- The scheme team will assign ECRs to mentors based on the information given while signing-up to the mentor scheme. Efforts will be made to match individuals as best as possible to interests, but this may not always be possible.
- During the conference there will be a short introductory session which provides guidance on what the scheme involves, and allows mentees to meet their mentors.
- After the conference, the expectation is that mentees will lead any contact with their mentor – e.g. send an email to introduce themselves, ask for some guidance or similar when they would like to. A mentor does not replace a tutor or supervisor (where applicable).
- If you have previously enrolled in the scheme as a mentee and would like to again and be assigned a different mentor, please sign-up. If you are happy with your existing mentor, no action is required if you both agree you would like to continue (though this should not be expected).
- Mentors will be allocated no more than 3 mentees and will be expected to meet with mentees at least once during GISRUK and should try and engage with mentees at least once more during the 12 month period (in-person or online).

# Eligibility 

- You should be registered and attending the GISRUK 2025 conference in Bristol.
- Mentees – To register as a mentee you should consider yourself an ECR (Early Career Researcher).
- Mentors – To register as a mentor, you should consider yourself ‘established’ in your field—determined by the norms of your position (e.g. the criteria for this may be different in academia and industry). You should be willing to commit a few hours over the next 12 months to engage with any mentees you are assigned, and be able to give advice on a range of matters ECRs may wish to speak to you about.

# By signing up you also agree to the following: 

- In accordance with GDPR, details of all those who sign-up will be stored securely, will only be available to the scheme administrative team, and all details will be deleted within 18 months of the scheme starting. If anyone wishes to be removed from the scheme, or have their details deleted, they should contact the scheme team or GISRUK directly (info@gisruk.org). 
- GISRUK is not responsible for the conduct of those who are members of the scheme as either mentors or mentees. If in any circumstances an individual is concerned or affected by the behaviour or conduct of someone, a mentor or mentee, this should be reported immediately to someone in a position of responsibility as well as the scheme team or GISRUK directly (info@gisruk.org).

